pipeline {
    agent { docker 'maven:3.3.3' }
    options { timestamps() }
    stages {
        stage('build') {
            steps {
                sh 'cd PictorialArt; mvn clean install'
            }
        }
    }
}